name: Deploy to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Deploy via SSH
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: 16.170.221.67
          username: ubuntu
          key: ${{ secrets.EC2_KEY }}
          script: |
            if [ ! -d /home/ubuntu/Steam_Clone/.git ]; then
              rm -rf /home/ubuntu/Steam_Clone
              git clone https://github.com/SakshamGupta-1904/Steam_Clone.git /home/ubuntu/Steam_Clone
            else
              cd /home/ubuntu/Steam_Clone
              git reset --hard HEAD
              git clean -fd
              git pull origin main
            fi

            cd /home/ubuntu/Steam_Clone
            docker stop my-app || true
            docker rm my-app || true
            docker ps -q --filter "publish=80" | xargs -r docker stop
            docker ps -aq --filter "publish=80" | xargs -r docker rm
            docker build -t my-app .
            docker run -d --name my-app -p 80:80 my-app